title: SDU Combinatorics Group | Guanghui Wang
page-top-title: SDU Comb Group
home-subtitle: SDU Combinatorics Group (Prof. Guanghui Wang)
copyright-text: '&copy; Guanghui Wang 2026. All Rights Reserved.'
