title: SDU Combinatorics Group | Guanghui Wang
page-top-title: SDU Comb Group
home-subtitle: SDU Combinatorics Group (Prof. Guanghui Wang) &ensp;|&ensp; 山东大学组合数学研究组（王光辉）
copyright-text: '&copy; Guanghui Wang 2026. All Rights Reserved.'
